import { defineConfig, devices } from '@playwright/test';

/**
 * Playwright config for the DevAtlas e2e suite.
 *
 * The suite runs against the SHIPPED artifact: the static export generated by
 * `next build` (output: 'export') into `frontend/out/`, served locally at the
 * same port CI uses. Build before running locally:
 *
 *   npm run build && npm run e2e
 *
 * CI starts `npx --yes serve@14 out -l 4173` itself and this config reuses it
 * (see the `smoke` job in .github/workflows/ci.yml).
 */

const PORT = 4173;
const BASE_URL = `http://localhost:${PORT}`;

export default defineConfig({
  testDir: './e2e',
  timeout: 60000, // 1 minute per test (animations take time)
  expect: {
    timeout: 10000
  },
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'list',
  use: {
    actionTimeout: 0,
    baseURL: BASE_URL,
    trace: 'on-first-retry',
    screenshot: 'on',
    video: 'off',
  },
  // Serve the exported bundle exactly as deployed. `reuseExistingServer` keeps
  // this from double-binding the port when CI has already started the server.
  webServer: {
    command: `npx --yes serve@14 out -l ${PORT}`,
    url: BASE_URL,
    reuseExistingServer: true,
    timeout: 120_000,
  },
  projects: [
    {
      name: 'smoke',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: BASE_URL,
        viewport: { width: 1920, height: 1080 }
      },
    },
    {
      // Mobile viewport check. Pinned to Chromium on purpose: CI installs only
      // `chromium` (`npx playwright install --with-deps chromium`), so the
      // device's default WebKit engine is unavailable and would fail the run.
      name: 'smoke-mobile',
      use: {
        ...devices['iPhone 13'],
        browserName: 'chromium',
        baseURL: BASE_URL,
      },
    },
  ],
});
